"""temporarily remove unique

Revision ID: 4a20c50ad7c3
Revises: 617fa7f5a12a
Create Date: 2018-12-11 15:24:02.056270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a20c50ad7c3'
down_revision = '617fa7f5a12a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_companies_companyName', table_name='companies')
    op.create_index(op.f('ix_companies_companyName'), 'companies', ['companyName'], unique=False)
    op.drop_index('ix_companies_symbol', table_name='companies')
    op.create_index(op.f('ix_companies_symbol'), 'companies', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_symbol'), table_name='companies')
    op.create_index('ix_companies_symbol', 'companies', ['symbol'], unique=True)
    op.drop_index(op.f('ix_companies_companyName'), table_name='companies')
    op.create_index('ix_companies_companyName', 'companies', ['companyName'], unique=True)
    # ### end Alembic commands ###
