"""empty message

Revision ID: 82f59009cbe1
Revises: 4a20c50ad7c3
Create Date: 2018-12-11 23:05:51.024067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82f59009cbe1'
down_revision = '4a20c50ad7c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_companies_companyName', table_name='companies')
    op.create_index(op.f('ix_companies_companyName'), 'companies', ['companyName'], unique=True)
    op.drop_index('ix_companies_symbol', table_name='companies')
    op.create_index(op.f('ix_companies_symbol'), 'companies', ['symbol'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_symbol'), table_name='companies')
    op.create_index('ix_companies_symbol', 'companies', ['symbol'], unique=False)
    op.drop_index(op.f('ix_companies_companyName'), table_name='companies')
    op.create_index('ix_companies_companyName', 'companies', ['companyName'], unique=False)
    # ### end Alembic commands ###
